# permissions for end users to view secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: secret-viewer-role
rules:
- apiGroups:
  - secrets-distributor.z2h.dev
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets-distributor.z2h.dev
  resources:
  - secrets/status
  verbs:
  - get
