apiVersion: v1
kind: Namespace
metadata:
  name: system-secret-meta
---
apiVersion: v1
kind: Secret
metadata:
  name: app1-db-creds
  namespace: system-secret-meta
  annotations:
    secrets-distributor.z2h.dev/target-namespace: app1
    secrets-distributor.z2h.dev/target-cluster: local-dev
    secrets-distributor.z2h.dev/secret-types: "k8s"
    secrets-distributor.z2h.dev/owner: team-alpha
type: Opaque
data:
  username: YXBwMXVzZXI=  # app1user
  password: YXBwMXBhc3M=  # app1pass
---
apiVersion: v1
kind: Secret
metadata:
  name: app2-api-keys
  namespace: system-secret-meta
  annotations:
    secrets-distributor.z2h.dev/target-namespace: app2
    secrets-distributor.z2h.dev/target-cluster: aws-prod-1
    secrets-distributor.z2h.dev/secret-types: "k8s,openbao"
    secrets-distributor.z2h.dev/owner: team-beta
type: Opaque
data:
  api_key: a2V5MTIz      # key123
  api_secret: c2VjcmV0NDU2  # secret456
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-oauth-config
  namespace: system-secret-meta
  annotations:
    secrets-distributor.z2h.dev/target-namespace: shared-services
    secrets-distributor.z2h.dev/target-cluster: aws-prod-1
    secrets-distributor.z2h.dev/secret-types: "k8s,aws-sm"
    secrets-distributor.z2h.dev/owner: team-platform
type: Opaque
data:
  client_id: b2F1dGhfY2xpZW50        # oauth_client
  client_secret: b2F1dGhfc2VjcmV0    # oauth_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: cross-cluster-db
  namespace: system-secret-meta
  annotations:
    secrets-distributor.z2h.dev/target-namespace: database
    secrets-distributor.z2h.dev/target-cluster: gcp-prod-2
    secrets-distributor.z2h.dev/secret-types: "k8s,aws-sm"
    secrets-distributor.z2h.dev/owner: team-dba
type: Opaque
data:
  db_user: YWRtaW4=       # admin
  db_password: c2VjdXJlcGFzcw==  # securepass
