apiVersion: secrets-distributor.z2h.dev/v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: secret-sample
spec:
  # TODO(user): Add fields here
